#ARG IMAGE=nanoramic/odoo-base
#FROM $IMAGE
FROM 205791896111.dkr.ecr.us-east-1.amazonaws.com/nanoramic:base

USER root
RUN mkdir /code
RUN chown -R odoo /code
USER odoo
ADD enterprise /code/enterprise
